#!/bin/sh

alias clip="xclip -selection clipboard -i"
alias p="ping 9.9.9.9"
alias ping="ping -c 5"
alias md="mkdir -p"

mcd() {
	mkdir -p "$@" && cd "$@" || return
}

# Editor alias
alias e='$EDITOR'
alias sudoe="EDITOR=nvim sudo -e "
alias pb="nc termbin.com 9999" # pasting from terminal

if command -v rg >/dev/null 2>&1; then
	alias grep="rg"
else
	alias grep="grep --line-number --ignore-case --color=auto --exclude-dir={.git}"
fi

# Highlight with less
alias highlight="highlight --force -O xterm256 --style molokai"

# {{{ Directory Navigation
if command -v exa >/dev/null 2>&1; then
	alias ls="exa --group-directories-first --icons"
else
	alias ls="ls --group-directories-first --color=always "
fi
alias l="ls -lh"
alias ll='ls -lah'
alias la="l -a"
alias sl=ls
alias d='dirs -v'

if command -v batcat >/dev/null 2>&1; then
	alias bat='batcat'
	alias cat='bat -pp'
	alias catt='bat'
	alias less='bat'
elif command -v bat >/dev/null 2>&1; then
	alias cat='bat -pp'
	alias catt='bat'
	alias less='bat'
else
	alias less='less -R'
fi
#}}}

# {{{ Git Aliases
source ~/.config/shell/git.sh
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gba="git branch --all"
alias gbd="git branch -d"
alias gbD="git branch -D"
alias gcp="git cherry-pick"
alias gre="git restore"
alias grs="git restore --staged"
alias grea="git restore ."
alias gpr="git remote prune origin"
alias gc="git commit -m"
alias gca="git commit --amend"
alias gcan='git commit --amend --no-edit'
alias gco="git checkout"
alias gsw="git switch"
alias gsc="git switch -c"
alias gcm="git checkout master"
alias gd="git diff -w"
alias gds="git diff -w --staged"
alias gs="git status -sb"
alias gcl="git clone"
alias gst="git stash"
alias gstp="git stash push"
alias gstpo="git stash pop"
alias ff="gpr && git pull --ff-only"
alias gpull="git pull"
alias gpush="git push"
alias gl="git lg"
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias git-current-branch="git branch | grep \* | cut -d ' ' -f2"
alias gup='git branch --set-upstream-to=origin/$(git-current-branch) $(git-current-branch)'
alias gu='git reset --soft HEAD~1'
# }}}

# {{{ Trash-cli Aliases
if command -v trash >/dev/null 2>&1; then
	alias rd="trash-put"
	alias rm="trash-put"
	alias trp="trash-put"
	alias tre='trash-empty'
	alias trl='trash-list'
	alias trr='trash-restore'
	alias trm='trash-rm'
else
	alias rd="rmdir"
	alias rm="rm -Iv"
fi
#}}}

alias ta="tmux attach -t"
alias xclip="xclip -selection clipboard"
alias clip="tee >(xclip)"

# vim: fdm=marker ft=sh
