#!/bin/sh

alias clip="xclip -selection clipboard -i"
alias p="ping 9.9.9.9"
alias ping="ping -c 5"
alias md="mkdir -p"

mcd() {
	mkdir -p "$@" && cd "$@" || return
}

# Editor alias
alias lvim="NVIM_APPNAME=lvim nvim"
alias e="$EDITOR"
alias le="lvim"
alias sudoe="EDITOR=lvim sudo -e "
alias pb="nc termbin.com 9999" # pasting from terminal

if command -v rg &>/dev/null ; then
	alias grep="rg"
else
	alias grep="grep --line-number --ignore-case --color=auto --exclude-dir={.git}"
fi

# Highlight with less
alias highlight="highlight --force -O xterm256 --style molokai"

# {{{ Directory Navigation
if command -v exa >/dev/null; then
	alias ls="exa --group-directories-first --icons"
else
	alias ls="ls --group-directories-first --color=always "
fi
alias l="ls -lh"
alias ll='ls -lah'
alias la="l -a"
alias d='dirs -v'

if command -v batcat &> /dev/null; then
	alias bat='batcat'
fi
if command -v bat &> /dev/null; then
	alias bat='bat --theme "Visual Studio Dark+"'
	alias cat='bat --pp'
	alias catt='bat'
	alias less='bat'
else
	alias less='less -R'
fi
#}}}

# {{{ Git Aliases
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gre="git restore"
alias gres="git restore --staged"
alias grea="git restore ."
alias gc="git commit -m"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gcom="git checkout master"
alias gd="git diff"
alias gs="git status -sb"
alias gca="git commit --amend"
alias gcl="git clone"
alias gst="git stash"
alias gstp="git stash push"
alias gstpo="git stash pop"
alias gpull="git pull"
alias gpush="git push"
alias gl="git log --format=format:'%C(auto)%h %C(green)%aN%Creset %Cblue%cr%Creset %s'"
# }}}

# {{{ Trash-cli Aliases
if command -v trash >/dev/null 2>&1; then
	alias rd="trash-put"
	alias rm="trash-put"
	alias trp="trash-put"
	alias tre='trash-empty'
	alias trl='trash-list'
	alias trr='trash-restore'
	alias trm='trash-rm'
else
	alias rd="rmdir"
	alias rm="rm -Iv"
fi
#}}}

# vim: fdm=marker
