#!/bin/sh
# File              : pacman
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 07.07.2018
# Last Modified Date: 07.07.2018
# Last Modified By  : Samyak Puri <samyakpuri@hotmail.com>

# case $BLOCK_BUTTON in
#     1) $TERMINAL -e pulsemixer & disown ;;
#     3) pamixer -t ;;
#     4) pamixer -i 5 ;;
#     5) pamixer -d 5 ;;
# esac

[ "$BLOCK_BUTTON" = "1" ] && $TERMINAL -e sudo pacman -Syu && pacman -Qu | wc -l > ~/.pacupgrade && pkill -RTMIN+8 i3blocks

pacman -Qu | wc -l > ~/.pacupgrade && pkill -RTMIN+8 i3blocks

cat ~/.pacupgrade
