#!/bin/sh

# i3blocks weather block using wttr.in

location="passau"

[ "$BLOCK_BUTTON" = "1"  ] && st -e w3m wttr.in/${location}

ping -q -w 1 -c 1 "$(ip r | grep default | cut -d ' ' -f 3)" >/dev/null || exit

if [ "$location" != ""  ]
then
    location="${location}?0QT"
fi

curl "wttr.in/${location}" > /tmp/wttr

(grep -F "mm" /tmp/wttr > /dev/null ) && [ ! $? ] && exit

SUNNY=""
CLOUDY=""
RAINY=""
STORM=""
SNOW=""
FOG=""

icon=$(sed -r -e "1!d;s/^.\{15\}//;s/.*[cC]loudy|[oO]vercast.*/$CLOUDY/;s/.*[sS]unny|[cC]lear.*/$SUNNY/;s/.*[rR]ainy.*/$RAINY/;\
s/.*[sS]now.*/$SNOW/;s/.*[fF]og.*/$FOG/" /tmp/wttr)

temp=$(sed -e '2!d;s/^.\{15\}//;s/[ \t]\+$//' /tmp/wttr)
echo "$icon   $temp"
