#!/bin/sh


alias \
	clip="xclip -selection clipboard -i" \
	p="ping 9.9.9.9" \
	ping="ping -c 5" \
	md="mkdir -p" \
	rd="rmdir" \
	rm="rm -Iv"

# Editor alias
alias \
	vim=$EDITOR \
	e=vim \
	edit=vim \
	pb="nc termbin.com 9999" # pasting from terminal

# alias grep="grep --line-number --ignore-case --color=auto --exclude-dir={.git}"
alias grep="rg"
# Highlight with less
alias highlight="highlight --force -O xterm256 --style molokai"

#{{{ Directory Navigation
	alias \
		ls="ls --color=always" \
		l="ls -lh" \
		ll='ls -lah' \
		less="less -R" \
		d='dirs -v' 
	for index ({1..9}) alias "$index"="cd +${index}"; unset index
#}}}

#{{{ Git Aliases
	alias \
		g="git" \
		ga="git add" \
		gb="git branch" \
		gre="git restore" \
		gres="git restore --staged" \
		grea="git restore ." \
		gc="git commit -m" \
		gco="git checkout" \
		gcb="git checkout -b" \
		gcom="git checkout master" \
		gs="git status -sb" \
		gca="git commit --amend" \
		gcl="git clone" \
		gst="git stash" \
		gstp="git stash push" \
		gstpo="git stash pop" \
		gpull="git pull" \
		gpush="git push" \
		gl="git log --format=format:'%C(auto)%h %C(green)%aN%Creset %Cblue%cr%Creset %s'"
# }}}
