## Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# prompt
format = """\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$all\
$cmd_duration $jobs $time\
$line_break\
$character\
"""

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "❯"
[character]
success_symbol = "[λ](white)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](blue)"

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
truncation_length = 1
truncate_to_repo = false

[fill]
symbol = " "

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold white"
time_format = "%d/%m/%Y %H:%M"
format = "[$time]($style)"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[hostname]
ssh_only = true
format = "@[$hostname$ssh_symbol]($style) "
style = "green bold"
trim_at = "."
disabled = false

[username]
style_user = "cyan bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

# "bold red" style when capacity is between 0% and 20%
[[battery.display]]
threshold = 20
style = "bold red"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = true

# Clear visibility for exit codes
[status]
style = "red"
symbol = "💣 "
format = '[\[$symbol$status\]]($style) '
disabled = false

[aws]
symbol = "  "
format = "[$symbol]($style)"

[buf]
symbol = " "
format = "[$symbol]($style)"

[c]
symbol = " "
format = "[$symbol]($style)"

[cmake]
format = "[$symbol]($style)"
disabled = true

[conda]
symbol = " "
format = "[$symbol]($style)"

[dart]
symbol = " "
format = "[$symbol]($style)"

[docker_context]
symbol = " "
format = "[$symbol]($style)"

[elixir]
symbol = " "
format = "[$symbol]($style)"

[elm]
symbol = " "
format = "[$symbol]($style)"

# [fossil_branch]
# symbol = " "
# format = "[$symbol]($style)"

# [git_branch]
# symbol = " "

[golang]
symbol = " "
format = "[${symbol}${version}]($style)"

[guix_shell]
symbol = " "
format = "[${symbol}${version}]($style)"

[haskell]
symbol = " "
format = "[${symbol}${version}]($style)"

[haxe]
symbol = "⌘ "
format = "[${symbol}${version}]($style)"

[hg_branch]
symbol = " "
format = "[${symbol}${version}]($style)"

[java]
symbol = " "
format = "[${symbol}${version}]($style)"

[julia]
symbol = " "
format = "[${symbol}${version}]($style)"

[lua]
symbol = " "
format = "[${symbol}${version}]($style)"

[memory_usage]
symbol = "󰗗 "
format = "[${symbol}${version}]($style)"

[meson]
symbol = "喝 "
format = "[${symbol}${version}]($style)"

[nim]
symbol = " "
format = "[${symbol}${version}]($style)"

[nix_shell]
symbol = " "
format = "[${symbol}${version}]($style)"

[nodejs]
symbol = " "
format = "[${symbol}${version}]($style)"

[package]
symbol = " "
format = "[${symbol}${version}]($style)"

# [pijul_channel]
# symbol = "🪺 "
# format = "[${symbol}${version}]($style)"

[python]
symbol = " "
format = "[${symbol}${version} (\\($virtualenv\\) )]($style)"

[rlang]
symbol = "󰟔 "
format = "[${symbol}${version}]($style)"

[ruby]
symbol = " "
format = "[${symbol}${version}]($style)"

[rust]
symbol = " "
format = "[${symbol}${version}]($style)"

[scala]
symbol = " "
format = "[${symbol}${version}]($style)"

[spack]
symbol = "🅢 "
format = "[${symbol}${version}]($style)"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[os]
format = "[$symbol]($style) "
disabled = false
