#!/bin/bash
# File              : dmenuumount
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 17.08.2018
# Last Modified Date: 17.08.2018
# Last Modified By  : Samyak Puri <samyakpuri@hotmail.com>

declare -A drives="($(df -h --output=source,target | awk '/\/run\/media/{ n=split($2,a,"/"); print "["a[n]"]="$1}'))"

chosen=$(echo "${!drives[@]}" | dmenu -i -p "Select drive to unmount: " | awk '{print $1}')
[ -z "$chosen" ] && exit 1
udisksctl unmount -b "${drives[${chosen}]}"
rm $HOME/${chosen}
