#!/bin/bash
# File              : battery
# Author            : Samyak Puri <samyakpuri@hotmail.com>
# Date              : 07.07.2018
# Last Modified Date: 07.07.2018
# Last Modified By  : Samyak Puri <samyakpuri@hotmail.com>

text=$(acpi | cut -d " " -f3-5 | sed -e "s/,//g;s/Discharging/🔋/;s/Charging/🔌/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")

if [ $(awk '{print $1}' <<< "$text") = '🔋' ];
then
    if [ ! -e /tmp/.batlow ]; then
        if [ $(awk '{print int(substr($2,1,length($2)-1))}' <<< "$text") -lt 15 ];
        then
            notify-send --urgency=critical "Battery Low"\
                "Plugin Charger"
            touch /tmp/.batlow
            beep
        fi
    fi
fi

echo $text
