#!/bin/sh

[ -f "$HOME/.config/shell/profile" ] && source "$HOME/.config/shell/profile"

# gnome-keyring-daemon --start -- components=pkcs11,secrets,ssh >/dev/null 2>&1 &

picom &          # xcompmgr for transparency
dunst &          # dunst for notifications
unclutter &      # Remove mouse when idle
sxhkd &          # sxhkd for keybindings
nm-applet &      # NetwokManager Applet
blueman-applet & # Bluetooth Manager
